import Head from 'next/head'
import Image from 'next/image'
import styles from './layout.module.css'
import utilStyles from '../styles/utils.module.css'
import Link from 'next/link'

const name = '[Your Name]'
export const siteTitle = 'Next.js Sample Website'

export default function Layout({ children, home }) {
  return (
    <div>
      <Head>
      <title>Bobby68</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/Axolotl_Logo.png" />
    </Head>
    <div className={styles.container}>
      <main>
      <div className={styles.navdiv}>
          <Link href="/" className={styles.navback}>
            <img height="30" src="../assets/Navigation/Home.png" alt="Home"/>
          </Link>
        <h1 className={styles.headline}> Nooble </h1>
        <div>
        <Link href="https://github.com/Filipza/LF3" className={styles.navback}>
            <img height="42" src="../assets/nooble/git.png" alt="git"/>
          </Link>
        <a href="/login" className={styles.navlogin}>
          <img height="40" src="../assets/Navigation/login.png" alt="Login"/>
        </a>
        </div>
      </div>
        {children}
        </main>
    </div>
  </div>
  )
}