import Head from "next/head"
import Image from "next/image"
import styles from "../styles/about_me.module.css"
import Link from "next/link"


export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Bobby68</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Axolotl_Logo.png" />
            </Head>

      <main className={styles.main}>

      <div className={styles.navdiv}>
          <Link href="/" className={styles.navback}>
            <Image height="30" src="../assets/Navigation/Home.png" alt="Home"/>
          </Link>

        <a href="/login">
          <Image height="30" src="../assets/Navigation/login.png" alt="Login"/>
        </a>
      </div>

      <span className={styles.head}>
            <Image src="/assets/about_me/header_image.png" alt="Bobby68" width={1000} height={150} />
          </span>
      
          <div className={styles.social}>
              <h1>💬 &nbsp;My Socialmedia&nbsp; 💬</h1>
        <hr className={styles.hr}/>
            <a href="https://discord.com/users/528982743623925781" target="_blank">
              <Image height="50" src="https://Image.icons8.com/color/344/discord-new-logo.png"/>
            </a>
            <a href="https://live.xbox.com/Profile?Gamertag=Bobby3498" target="_blank">
              <Image height="50" src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Xbox_one_logo.svg/2048px-Xbox_one_logo.svg.png"/>
            </a>
            <a href="https://github.com/luca-naujoks" target="_blank">
              <Image height="100" src="/assets/about_me/GitHub-Mark-Light-120px-plus.png"/>
            </a>
            <a href="https://www.instagram.com/anonymes_bobby68/" target="_blank">
              <Image height="50" src="https://user-images.githubusercontent.com/46517096/166974368-9798f39f-1f46-499c-b14e-81f0a3f83a06.png"/>
            </a>
            <a href="https://www.youtube.com/channel/UCjPMp9s9WDkeJy2Ta5vjh0A/featured" target="_blank">
              <Image height="50" src="https://cdn-icons-png.flaticon.com/512/1384/1384060.png"/>
            </a>
        </div>

        <p className={styles.gif}>
            <Image src="/assets/about_me/sinon.gif" alt="Sinon" width={500} height={280}/>
          </p>
        
        <hr className={styles.hr}/>

        
        <h2 > 👨🏻‍💻 &nbsp;A Little Bit About Me And My Interests</h2>
 
            <div className={styles.info}>
                <p></p>
                <div className={styles.infotext}>
                    <p></p>
                        <br></br>
                        <div><span className={styles.pl_ent}>name</span>: <span className={styles.pl_s}>Luca Naujoks</span></div>
                        <div><span className={styles.pl_ent}>current_job</span>: <span className={styles.pl_s}>Specialist for system integration</span></div>
                        <p></p>
                        <span className={styles.pl_ent}>company</span>: <span className={styles.pl_s}>Thinformatics</span>
                        <p></p>
                        <div><span className={styles.pl_ent}>fields_of_interests</span>:</div>
                        <div><span className={styles.pl_s}>[</span></div>
                        <div><span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Web Development<span className={styles.pl_pds}>"</span></span><span className={styles.pl_s}>,</span></div>
                        <div><span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Data Science<span className={styles.pl_pds}>"</span></span><span className={styles.pl_s}>,</span></div>
                        <div><span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Machine Learning<span className={styles.pl_pds}>"</span></span><span className={styles.pl_s}>,</span></div>
                        <div><span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Game Development<span className={styles.pl_pds}>"</span></span><span className={styles.pl_s}>,</span></div>
                        <div><span className={styles.pl_s}>]</span></div>
                        <div><span className={styles.pl_ent}>technical_background</span>:</div>
                        <div><span className={styles.pl_s}>[</span></div>
                        <div> <span className={styles.pl_s}><span className={styles.pl_pds1}>"</span>IT system electronics technician<span className={styles.pl_pds}>"</span></span></div>
                        <div><span className={styles.pl_s}>]</span></div>
                        <div></div>
                        <div><span className={styles.pl_ent}>currently_learning</span>: <span className={styles.pl_s}>["Docker, Angular"]</span></div>
                        <div><span className={styles.pl_ent}>2022 Goals</span>: <span className={styles.pl_s}>["Learn Angular and progress in Docker"]</span></div>
                        <div><span className={styles.pl_ent}>hobbies</span>: <span className={styles.pl_s}>["Gaming", "Programming", "Firefighter", "Diving", "play with hardware"]</span></div>
                        <br></br>
                </div>
            </div>

            <hr className={styles.hr}/>

            <h2> 🚀 &nbsp;Some Tools / Languages I Use&nbsp; 🚀</h2>
              <p align="left">
                <Image src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg" alt="vscode" width="45" height="45"/>
                <Image src="https://upload.wikimedia.org/wikipedia/commons/1/1d/PyCharm_Icon.svg"
                alt="PyCharm" width="45" height="45"/>
                <Image src="https://upload.wikimedia.org/wikipedia/commons/9/9c/IntelliJ_IDEA_Icon.svg"
                alt="IntelliJ" width="45" height="45"/>
              </p>
              
              <p align="left">
                <Image src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg" alt="docker" width="45" height="45"/>
                <Image src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg" alt="linux" width="45" height="45"/>
                <Image src="https://www.kim-bewertung.de/wp-content/uploads/2021/06/Windows-10-Icon.png" alt="Windows" width="45" height="45"/>
                <Image src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Icon-Mac.svg/256px-Icon-Mac.svg.png"
                alt="Mac OS/IOS" width="45"height="45"/>
              </p>
              
              <p align="left">
                <Image src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original-wordmark.svg" alt="python" width="45" height="45" />
                <Image src="https://cdn-icons-png.flaticon.com/512/5968/5968282.png" alt="python" width="45" height="45" />
                <Image src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" alt="javascript" width="45" height="45" />
                <Image src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" alt="html" width="45" height="45"/>
                <Image src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg" alt="css3" width="45" height="45" />
              </p>
              
              <p align="left">
                <Image src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg" alt="git" width="45" height="45"/>
                <Image src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg" alt="mysql" width="45" height="45" />
              </p>





        </main>
        </div>
    )
    
}