import Head from "next/head";
import Image from "next/image";
import Link from "next/link";


export default function Home() {
return (
  <div className="m-5">
    <Head>
            <title>Bobby68</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/Axolotl_Logo.png" />
          </Head>

          <main className="bg-black">
            <div className="flex justify-between">
              <Link href="/">
                <img
                  src="../assets/Navigation/Home.png"
                  alt="Home"
                  href="/"
                  className="xs:h-5 md:h-10 hover:scale-125 transition duration-700 ease-in-out"
                />
              </Link>

              <img
                src="/assets/about_me/header_image.png"
                alt="Bobby68"
                className="xs:w-2/3 md:w-1/2"
              />

              <Link href="">
                <img
                  src="../assets/Navigation/login.png"
                  alt="Login"
                  href=""
                  className="xs:h-5 md:h-10 hover:scale-125 transition duration-700 ease-in-out"
                />
              </Link>
            </div>


          <master>
            <div className="">
              
            
            </div>


          </master>



    </main>
  </div>
)

}


  