import Head from "next/head"
import Image from "next/image"
import Link from "next/link"


export default function bobbybot() {
    return (
        <div className="m-5">
            <Head>
                <title>Bobby68</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Axolotl_Logo.png" />
            </Head>

      <main className="bg-black px-[5%]">
      <div className="flex justify-between p-2.5">
          <Link href="/">
            <img  src="../assets/Navigation/Home.png" alt="Home"  className="h-10 hover:scale-125 transition duration-700 ease-in-out"/>
          </Link>
            <button className="bg-[transparent] border-none">
              <img src="../assets/Navigation/login.png" alt="Login" className="h-10 hover:scale-125 transition duration-700 ease-in-out"/>
            </button>
      </div>





      </main>
      </div>
    )
}