import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bobby68</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Axolotl_Logo.png" />
      </Head>

      <nav className={styles.mainnav}>
            <ul>
                <Link href='/'><a><li>Home</li></a></Link>
                <Link href='/login'><a><li>Login</li></a></Link>
            </ul>
        </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bobby68
        </h1>

        

        <div className={styles.grid}>
          <a href="/about_me" className={styles.card}>
            <h2>About Me &rarr;</h2>
            <p>Some Information About me and my Skills.</p>
          </a>

          <a href="/nooble" className={styles.card}>
            <h2>Nooble &rarr;</h2>
            <p>The Learning part of this website</p>
          </a>

        </div>
      </main>
    </div>
  )
}
