import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bobby68</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Axolotl_Logo.png" />
      </Head>

      <div className={styles.navdiv}>
        <div>
        <a href="/login" className={styles.nav}>
          <img height="40" src="../assets/Navigation/login.png" alt="Login"/>
        </a>
        </div>
      </div>

      <main className={styles.main}>
        <svg height="100%" width="100%" className={styles.svg}>
                  <clipPath id="text-overlay">
                      <text x="50%" y="50%" fill="red" text-anchor="middle">
                          Bobby68
                  </text>
                  </clipPath>
              </svg>

              <video autoPlay loop muted className={styles.video}>
              <source src="/assets/background.mp4" type="video/mp4"/>
              </video>

        <div className={styles.grid}>
          <a href="/about_me" className={styles.card}>
            <h2>About Me &rarr;</h2>
            <p>Some Information About me and my Skills.</p>
          </a>

          <a href="/nooble" className={styles.card}>
            <h2>Nooble &rarr;</h2>
            <p>The Learning part of this website</p>
          </a>

        </div>
      </main>
    </div>
  )
}
