import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/nooble.module.css'
import Link from 'next/link'
import Script from 'next/script'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bobby68</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Axolotl_Logo.png" />
      </Head>
      <main className={styles.main}>
    
      <div className={styles.navdiv}>
          <Link href="/" className={styles.navback}>
            <img height="30" src="../assets/Navigation/Home.png" alt="Home"/>
          </Link>
        
        <h1 className={styles.headline}> Nooble </h1>
        
        <a href="/login" className={styles.navlogin}>
          <img height="30" src="../assets/Navigation/login.png" alt="Login"/>
        </a>
      </div>
      <br></br>
      <hr/>
      <br></br>
       <div className={styles.info}>
       <div className={styles.infohead}><h2>LF 3 Networking</h2></div>
        <div className={styles.infotext}>
              <div><span className={styles.pl_ent}>berufsschule</span>: <span className={styles.pl_s}>Itech BS 14</span></div>
              <p></p>
              <span className={styles.pl_ent}>date</span>: <span className={styles.pl_s}>05.10-08.10.22, 24.10-10.11.22</span>
              <p></p>
              <div><span className={styles.pl_ent}>fields_of_interests</span>:</div>
              <div><span className={styles.pl_s}>[</span></div>
              <div><span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Web Development<span className={styles.pl_pds}>"</span></span><span className={styles.pl_s}>,</span></div>
              <div><span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Networking<span className={styles.pl_pds}>"</span></span><span className={styles.pl_s}>,</span></div>
              <div><span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Programming<span className={styles.pl_pds}>"</span></span><span className={styles.pl_s}>,</span></div>
              <div><span className={styles.pl_s}>]</span></div>
              <div><span className={styles.pl_ent}>technical_devices</span>:</div>
              <div><span className={styles.pl_s}>[</span></div>
              <div> <span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Rraspberry pis (4)<span className={styles.pl_pds}>"</span></span></div>
              <div> <span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>managed ethernet switch<span className={styles.pl_pds}>"</span></span></div>
              <div><span className={styles.pl_s}>]</span></div>
              <div></div>
              <div><span className={styles.pl_ent}>products</span>:</div>
              <div><span className={styles.pl_s}>[</span></div>
              <div> <span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>functional Network<span className={styles.pl_pds}>"</span></span></div>
              <div> <span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>ipv4 calculator<span className={styles.pl_pds}>"</span></span></div>
              <div> <span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Next js website<span className={styles.pl_pds}>"</span></span></div>
              <div><span className={styles.pl_s}>]</span></div>
              <br></br>
              <a href="/index.html">calculator</a>
        </div>
       </div>

      <br></br>
      <hr/>
      <br></br>

       <div className={styles.info}>
        <div className={styles.infohead}><h2>LF 5 Database</h2></div>
        <div className={styles.infotext}>
              <div><span className={styles.pl_ent}>berufsschule</span>: <span className={styles.pl_s}>Itech BS 14</span></div>
              <p></p>
              <span className={styles.pl_ent}>date</span>: <span className={styles.pl_s}>15.06-06.07.22</span>
              <p></p>
              <div><span className={styles.pl_ent}>fields_of_interests</span>:</div>
              <div><span className={styles.pl_s}>[</span></div>
              <div><span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Programm Development<span className={styles.pl_pds}>"</span></span><span className={styles.pl_s}>,</span></div>
              <div><span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>SQL Database controll<span className={styles.pl_pds}>"</span></span><span className={styles.pl_s}>,</span></div>
              <div><span className={styles.pl_s}>]</span></div>
              <div><span className={styles.pl_ent}>technical_devices</span>:</div>
              <div><span className={styles.pl_s}>[</span></div>
              <div> <span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Rraspberry pis (3)<span className={styles.pl_pds}>"</span></span></div>
              <div><span className={styles.pl_s}>]</span></div>
              <div></div>
              <div><span className={styles.pl_ent}>products</span>:</div>
              <div><span className={styles.pl_s}>[</span></div>
              <div> <span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>functional database<span className={styles.pl_pds}>"</span></span></div>
              <div> <span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>database controll programm<span className={styles.pl_pds}>"</span></span></div>
              <div> <span className={styles.pl_s}><span className={styles.pl_pds1}> "</span>Python<span className={styles.pl_pds}>"</span></span></div>
              <div><span className={styles.pl_s}>]</span></div>
              <br></br>
        </div>
       </div>

      </main>
    </div>
  )

}